plugins {
    id("io.micronaut.library") version "4.4.0"
    id("com.github.johnrengelman.shadow") version "7.1.2"
}

version = "0.1"
group = "example.micronaut"

repositories {
    mavenCentral()
}

dependencies {
    // lombok
    annotationProcessor "org.projectlombok:lombok:1.18.24"
    implementation("org.projectlombok:lombok:1.18.24")
    // org.json
	implementation 'org.json:json:20220320'
    
    implementation("com.amazonaws:aws-lambda-java-events:3.11.0")
    implementation("io.micronaut:micronaut-jackson-databind")
    implementation("jakarta.annotation:jakarta.annotation-api")
    runtimeOnly("ch.qos.logback:logback-classic")
    implementation("io.micronaut.validation:micronaut-validation")
    implementation("io.micronaut.aws:micronaut-function-aws")
    implementation("io.micronaut.aws:micronaut-function-aws-custom-runtime")
    implementation("io.opentelemetry:opentelemetry-api:1.45.0")

    // DB
    implementation("org.mybatis:mybatis:3.5.16")
    implementation("io.micronaut:micronaut-http-client")
    implementation("io.micronaut:micronaut-jackson-databind")
    
    testImplementation("io.micronaut:micronaut-http-client")
    testImplementation("org.testcontainers:junit-jupiter")
    testImplementation("org.testcontainers:testcontainers")
    testImplementation "org.junit.jupiter:junit-jupiter:5.8.2"
}


java {
    sourceCompatibility = JavaVersion.toVersion("17")
    targetCompatibility = JavaVersion.toVersion("17")
}

micronaut {
    runtime("lambda_java")
    testRuntime("junit5")
    processing {
        incremental(true)
        annotations("example.micronaut.*")
    }
}


tasks.named("assemble") {
    dependsOn(":shadowJar")
}

tasks.named("shadowJar") {
    manifest {
        attributes("Main-Class": "example.micronaut.FuncRuntime")
    }
}

compileJava.options.encoding = 'UTF-8'
compileTestJava.options.encoding = 'UTF-8'
javadoc.options.encoding = 'UTF-8'
